networks:
  monitoring:
    driver: bridge

services:
  grafana:
    image: grafana/grafana-enterprise
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - grafana_storage:/var/lib/grafana
    networks:
      - monitoring
    depends_on:
      - loki
    
  loki:
    image: grafana/loki:3.0.0
    container_name: loki
    ports:
      - "3100:3100"
    # volumes:
      # - ./loki-config.yaml:/etc/loki/local-config.yaml
    # command: -config.file=/etc/loki/local-config.yaml
    networks:
      - monitoring

volumes:
  grafana_storage: 